- .gitignore
- slider.js
- test.html
- test.js
Added support for passing $event and value to all event callbacks.
> Callback value and event support

- slider.js
- test.html
- test.js
Added check to detect if updateevent attribute is an array and update model for each event passed, also added test cases.
> Added support to update model value for multiple events

- slider.js
You can try it on Plunker: http://plnkr.co/edit/p1DuMsKRfiYjarPomXUF?p=preview
See also: #26
> Support AngularJS 1.3 and bootstrap-slider 4.0

- slider.js
- test.html
- test.js
Created functions for setting options and applying default values.
Added extra checks for initiating value when using range, $scope.value could become [null, #] and lower handle could not be moved.
Added deregister functions for ngModel and ngDisabled watchers to prevent memory leaks when initiating the plug-in over and over.
Rewritten the test app to be able to test setting all of the options available in the jQuery plug-in.
> Restructured code without changing features

- README.md
- slider.js
A solution for the issue #58 : Attribute tooltip in conflict
https://github.com/seiyria/angular-bootstrap-slider/issues/58
> Add an alternative for tooltip conflict

- bower.json
> Need a new version for use latest fixes

- slider.js
Use on-slide, on-start-slide, on-stop-slide instead of onslide, onstartslide, and onstopslide
> Changed event attribute names

- slider.js
According changes in bootstrap slider events:
https://github.com/seiyria/bootstrap-slider#events
> Fixed setting model's value

- slider.js
Added new tooltip position option that has been added to bootstrap-slider
> Added tooltip position option setter

- bower.json
Enables newer version to be installed via bower with new features like the tooltip position
> Bumped seiyria-bootstrap-slider dependency

- slider.js
> fixed issue with slide events not passing values

- slider.js
fix for: Can't use step size > 20 due to Number.toFixed limitation #92
> fix for #92

- bower.json
I guess it works pretty well so far
> Update Bower dependencies

- slider.js
removed flickering when sliding fast. imho no harm done.
> removed unnecessary timeouts

- slider.js
As described in the issue, this is the fix of the broken formatter.
Cheers!
> Issue #108 Fix tooltip formatter

- .gitignore
- bower.json
- e2e-tests/protractor.conf.js
- e2e-tests/scenarios.js
- package.json
- slider.js
- test.html
first e2e test for tooltip external variables update
> first e2e test

- slider.js
Added support for the focus attribute to the slider directive. As per other attributes, pulling value from attribute into $scope and setting option via setOption().
> Added focus support to Angular directive

- slider.js
Fixing digest for other elements working with the same angular model.
> Add .$apply method for digesting

- bower.json
- package.json
- slider.js
- Added 'slider:refresh' event
- Bumped version
> Added slider:refresh event

- bower.json
- package.json
- slider.js
Could we add yet another event to supported list please? Thanks in advance.
> + added slider:resize event

- bower.json
> Allow use of Angular 1.5

- slider.js
Hi ! I added support for the "rangeHighlights" attribute of bootstrap-slider. (Example 22 of [bootstrap-slider examples](http://seiyria.com/bootstrap-slider/).) 
Here is a [plunker to demonstrate a possible usage](https://plnkr.co/edit/7KrhGo?p=preview).
> Added support for bootstrap-slider "rangeHighlights" parameter.

- slider.js
Added option flag to the wrapper
Will need to be on hold until [this](https://github.com/seiyria/bootstrap-slider/pull/638) is merged into the master slider
> add ticks_tooltip to angular wrapper

- bower.json
- package-lock.json
- package.json
- test.html
I updated the dependencies so npm audit would be happy.
I added all the needed dependencies to packages.json so the test could be run.
I updated the test.html to reference the node_modules versions of the dependencies.
> Updated Dependencies 

- slider.js
I removed the legacy code dating back to Bootstrap-Slider (using jQuery version).  
Current project is using AngularJS.
> Fix issue #156 - remove the legacy code
