seiyria/angular-bootstrap-slider

slider.js

`angular.element` No longer supports the same query selectors as jQuery, so the directive was not actually finding the slider on the element.  Wrapping the raw angular element with jQuery fixes this.  It should be an ok fix since the supported version of bootstrap-slider requires jQuery anyway.

fixed support in angular 1.3

---

slider.js

From what I experienced, clicking on the bar without dragging the cursor doesn't trigger the scope update. If fixed it adding such listener, what do you think?

Missing change event handler

---

.gitignore
bower.json
slider.js
test.html
test.js

I've updated the slider and tests to work with the newest version of the bootstrap slider.
https://github.com/seiyria/angular-bootstrap-slider/issues/52

Updating bootstrap slider to v4.8

---

bower.json

We can confirm that angular-bootstrap-slider can work with AngularJS 1.3 and bootstrap-slider 4.4.0 at #38.
This pull request updates depended versions and bumps up angular-bootstrap-slider version.

Update dependencies to AngularJS 1.3.8 and bootstrap-slider 4.4.0

---

slider.js

changes in the result of the expression bound to the ng-disabled attribute haven't been reflected via data binding, e.g.:
`<slider ng-disabled="myController.myCondition">`
fixed it by adding "$parent." after "$scope"

fixed ngDisabled data binding

---

slider.js

Slider events defined as attributes were not being called. Updated
invoker function with proper signature.

Slider events not being called

---

bower.json

This little PR allows usage of this bower package in projects that use Angular 1.4.x without the need of coping with conflicting version requirements and adding resolutions.
Currently this component looks OK on Angular 1.4.0.

Allow use of Angular 1.4.x

---

slider.js

See https://docs.angularjs.org/api/ng/type/$rootScope.Scope#$watch.
Maybe we can use **$scope.$watchCollection**, but I'm not sure, what this does to normal sliders (not a range)

register the watch for array-elements.

---

slider.js

A $watch should be created directly on $scope, not on $scope.$parent. This is similar behavior to a few lines below when ngModel is also watched directly on $scope. Also cleaned up deregistering ngModel to match deregistering ngDisabled.

Move ngDisabled watcher to correct scope

---

slider.js

When using this directive as a range slider (i.e. setting range=true) bootstrap-slider plugin throws an error because it is expecting an array [min,max], not a float.
I just added a logic in ngModelDeregisterFn to not convert the ngModel value to float if the slider is a range slider.

prevents errors to be thrown when using the slider as a range slider

---

slider.js

When the max value for the slider is 0, it is taking the default value (since the condition checked falsy values). I just added a condition to determine whether the value is zero.

Take zero as a valid value when setting float option

---

slider.js

Step doesn't work with more than one decimal. e.g. with step = 0.01

issue with step with more than one decimal

---

test.html

Syntax Error: Token '{' invalid key at column 2 of the expression [{{ testOptions.ngDisabled }}] starting at [{ testOptions.ngDisabled }}].

quick fix in test

---

README.md
slider.js

angular directive's link function gets 'attrs' with normalized names (ie lowercase, without dashes) even though in the local  it's case sensative. also, send the name of the event along with the event value to the callback

event callbacks not triggered due to attribute naming issue

---

README.md
bower.json
package.json
slider.js

Reverting https://github.com/seiyria/angular-bootstrap-slider/pull/117 PR. 
Updated version, just in case if someone already used broken behaviour.

reverting pull/117

---

slider.js

This directive doesn't work for application built on AMD or CommonJs. If you take a look at source of bootstrap-slider.js (The actual plugin not the direcitve).
```
if (typeof define === "function" && define.amd) {
define(["jquery"], factory);
} else if ((typeof module === "undefined" ? "undefined" : _typeof(module)) === "object" && module.exports) {
var jQuery;
try {
jQuery = require("jquery");
} catch (err) {
jQuery = null;
}
module.exports = factory(jQuery);
} else if (window) {
window.Slider = factory(window.jQuery);
}
```
Your code depends on `window.Slider` and hence only works in case if you are not using any AMD or CommonJs loader. This commit fixes the issue.

Adding support for AMD & CommonJS.

---

slider.js

It should be this nomenclature to load properly with a tool like require.js

change the require string

---

slider.js

Changing the ticks array does not result in changes in the slider. This is useful because when ticks is set dynamically using the ticks array. The use case is the same as when the min/max properties are used. The `ticks` property overwrites the min/max property of slider which is already watched for.

Watch the ticks array for changes

---

package.json

From the looks of it, I don't think these dependencies are actually needed if one just wants to use this package, so I've moved them to `devDependencies`

move dependencies to devDependencies

---

slider.js

When $ exists in window, but not defined, an error would occur.
This checks whether it's actually defined before calling its function `$.fn.slider`

Check if jquery is defined
